### ISSUE TITLE
Site Logo not Showing

### ISSUE THREAD

**Issue by ghost** [sudo-nautilus/sudo-nautilus.github.io#2]
You may have to upload the image.jpg file as a PNG file. Since it's not showing on browser tabs, or maybe only for me🙄 it's not visible.
![IMG_20210425_204820_986](https://user-images.githubusercontent.com/77042574/115998996-96ce0c80-a607-11eb-839c-14aca7e7d9be.jpg)

**Comment by sudo-nautilus** [comment]
It's ok 😂
